### ISSUE TITLE
Fresh 4.0.2 install, can't search for gret functions

### ISSUE THREAD

**Issue by Jawkawmaw** [greisane/gret#16]
Hello!

I just downloaded blender 4.0.2 and tried to install gret 1.4.0 as well. 
Oddly enough, installing and enabling the addon wasn't a problem, but whenever I try to search for gret functions, they're not there.

I'm unsure what exactly causes this. I did have an old copy of blender 3.2 installed before, but no settings were imported from 3.2 to 4.0.2

Attempted fixes:
- Restarts of programs and restarts of PC
- Removing and reinstalling addon
- Uninstalling blender 3.2
- Uninstalling and reinstalling blender 4.0.2, followed by installing and enabling the addon once again

**Comment by greisane** [comment]
There used to be two search functions, one named *Search Menus* and another named *Search Operators*.
I guess Blender devs thought this was confusing so for 4.0 they removed the second one. I didn't notice because apparently with Developer Extras checked it enables the old functionality.
![image](https://github.com/greisane/gret/assets/59247540/e69f1a6c-fc11-4363-a917-3615778c0e69)

The addon should be working correctly for you, it's just that the simpler search won't let you find gret operators easily. You should be able to find them in their respective menus or the *gret* panel on the side.
![image](https://github.com/greisane/gret/assets/59247540/bf16ec64-598b-41a3-b2a4-91c99ce1aa94)

I'll amend the installation instructions, let me know if that was the only issue.

**Comment by Jawkawmaw** [comment]
Ah, that was indeed it! I can now use search with gret again. Thanks for the quick response, really appreciate it! 
Closing issue and marking as solved.
