### ISSUE TITLE
Apply Modfiers with Shapekey, but not Armature

### ISSUE THREAD

**Issue by fls-eugene** [greisane/gret#4]
Hello, is there a way to apply modifiers with Shapekey, but ignore Armature.

I need to apply mirror and subdiv for Fbx exports, and your plugin seems to be the most stable form all that I have tested.

Thanks

**Comment by greisane** [comment]
I've made this the default in 1b6fb4d726b967c667b8bf9eee01976e06d85ba9 since it's probably the expected behavior.

**Comment by cyaoeu** [comment]
I thought this addon was broken because of this, applying the armature modifier somehow broke the result of the operator removing all of the vertices.

Applying the armature modifier itself is a bit strange because if you were using one you would probably still want to have it (for example animating in Blender or exporting to a game engine and so on) and if you weren't using one you just don't add an armature modifier in the first place.

Having the addon disregard armature modifiers even if enabled would make it more newbie friendly since applying armature modifiers is such a rare workflow.

**Comment by greisane** [comment]
Agreed, it was very awkward. Added an user dialog in e1135cd935da0a0145a1e270e72c14be6f35bd40 that lets you select what to apply, armatures are excluded by default. As a bonus you can use `redo_last` to interactively see the result when toggling modifiers.

![image](https://user-images.githubusercontent.com/59247540/174934300-c772da7c-f4f7-4f79-b2f0-1710f2af2763.png)
